apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmap-watcher
  name: configmap-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-watcher
  template:
    metadata:
      labels:
        app: configmap-watcher
    spec:
      serviceAccountName: reader-watcher-lister-cm-secrets
      containers:
      - image: earthquakesan/configmap-watcher:latest
        name: configmap-watcher
        volumeMounts:
        - name: shared-volume
          mountPath: /config
      - name: kopf-sidecar
        image: omegavveapon/kopf-k8s-sidecar:1.3.4
        volumeMounts:
        - name: shared-volume
          mountPath: /config
        env:
        - name: LABEL
          value: "app"
        - name: LABEL_VALUE
          value: "configmap-watcher"
        - name: FOLDER
          value: /config/
        - name: RESOURCE
          value: configmap
        - name: NAMESPACE
          value: default
      volumes:
      - name: shared-volume
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-configmaps-secrets-get-watch-list
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reader-watcher-lister-cm-secrets
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-watcher-lister-cm-secrets-rolebind
roleRef:
  kind: ClusterRole
  name: role-configmaps-secrets-get-watch-list
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: reader-watcher-lister-cm-secrets
  namespace: default
