apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: configmap-watcher
  name: configmap-watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-watcher
  template:
    metadata:
      labels:
        app: configmap-watcher
    spec:
      containers:
      - image: earthquakesan/configmap-watcher:latest
        name: configmap-watcher
        volumeMounts:
        - name: config
          mountPath: "/config"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
            # items:
            # - key: "game.properties"
            #   path: "game.properties"
            # - key: "user-interface.properties"
            #   path: "user-interface.properties"
